import streamlit as st

st.title("我使用的Linux发行版")
st.subheader("1.由课程入门", divider=True)
st.write("我入门Linux是因为有课程要用到ROS，ROS虽然有Windows版本但对Windows的支持相对较差，就使用了Ubuntu。Ubuntu使用Gnome桌面，任务栏和软件列表等设计与Windows区别较大，不太习惯。后来课程结束就不再使用Ubuntu了。")
st.write("我使用Ubuntu的体验虽然不太好，但也算是入门了Debian系，了解了apt包管理器、输入法等内容，为后续独立探索其它Linux发行版做了准备。")
st.subheader("2.从主力到弃用", divider=True)
st.write("随着我对开源软件的了解增加，已经在大部分非互联网软件类型中改用开源软件，也希望再次使用开源的Linux系统。")
st.write("查阅资料后，我了解到Linux Mint是易用性较强的Linux发行版，相比大部分发行版外观有一定优势，就安装了Linux Mint22，并成功安装了所有需要使用的软件，部分互联网应用使用星火应用商店安装了wine版本。Linux Mint22使用的是Cinnamon桌面环境，操作上接近Windows系统，使用一些社区主题后总体外观优于当时用的Windows10。当时把Linux Mint22定为主力系统，虽然还有网友反映Windows11稳定性不佳，但考虑到外观优势还是把Windows系统更新到了Windows11。")
st.write("Linux Mint22在使用上也有不少方面体验优于Windows。安装Anaconda后在命令行中可以直接启动Python，而在Windows中需要单独的命令行程序。Linux支持brtfs文件系统，可以实现容量占用较少的快照功能，Linux Mint预装的timeshift能实现按计划创建快照。Cinnamon桌面环境虽然不是轻量化桌面，但流畅度相比Windows系统有优势，窗口可以缩小到较小尺寸并且不会出现还原后尺寸过大的问题。Linux Mint内置应用商店，系统设置中包含换源功能，换源后能快速加载软件详情，我这一时期从软件商店接触到了Xaos、Stellaarium和KDE Marble等优秀的开源软件。在Linux运行Comfyui相比Windows有10%到20%的速度优势，其它软件没有对比。")
st.write("我使用Linux Mint22也遇到了一些问题。Linux Mint内置了smb文件共享功能，但使用其它设备无法连接。Openwebui等在Windows上功能正常的应用也无法在其它设备连接。我用的笔记本电脑的厂商没有适配Linux的风扇转速和键盘灯控制程序，在同类开源软件中也找不到适配的方案。在Windows系统中安装Anaconda后通过conda和pip指令下载都能自动换源，但我在Linux Mint22中只给conda成功换源，pip换源没有效果。Linux上缺少Steam Community302等公开的加速器，在当时对代理服务器了解较少的情况下无法顺利使用GitHub。又因为Windows系统升级到Windows11并使用资源管理器高斯模糊等美化措施后外观有优势，就弃用了Linux。")
st.subheader("3.回归双系统", divider=True)
st.write("后来我了解了代理服务，在完成其它一些项目后有空闲的硬盘，为了进一步探索Linux和在Windows有故障时准备恢复措施，决定安装一个Linux发行版组双系统。")
st.write("开始时为了尝试平铺和浮动兼备的窗口管理，选择了使用测试版Cosmic DE的Pop!_OS。实际使用发现Cosmic DE的窗口管理的确能提高效率，但这一版本的Pop!_OS也存在不少软件无法正常使用，软件安装使用flatpak的空间占用较大，因此决定弃用。")
st.write("个人感觉DDE15桌面的外观比较好，就尝试了GXDE。GXDE是基于Debian12的使用DDE15桌面的Linux发行版，但在GXDE出现无法使用深色模式、系统内置播放器播放HDR视频卡顿的问题。又测试了Debian v23，DDE23桌面的外观不如DDE15，并且使用时遇到了系统内置播放器在界面缩放大于100%时播放视频分辨率下降的问题，也决定弃用了。")
st.write("后面了解到Fedora是偏上游并且易用的系统，使用Budgie桌面的版本操作方式接近Windows并且外观比较好，就安装了Fedora。相比deb系，在软件商店安装软件时不需要输入密码，安装快很多。但使用时遇到一个严重问题：系统自带的硬件解码只支持英特尔处理器，但我的电脑使用的是AMD的处理器，无法使用硬件解码，因此弃用了Fedora。")
st.write("最后还是决定装回Linux Mint，尝试了基于Debian的LMDE6，但出现了安装时没有中文以及部分软件功能不完善的问题（例如Xaos没有提供分形实例），就换成之前用过的Linux Mint22。这一次进一步探索了软件商店中的游戏列表，发现Linux上有比较完善的开源3D游戏，我玩的时间比较长的有Openarena和SuperTuxKart。")
st.subheader("4.新的物理机", divider=True)
st.write("由于我目前性能需求高的应用都在Windows上部署，AI视频等应用需要长时间运行，切换到Linux时不能继续使用这些应用，并且考虑到使用REFS数据盘、时间不统一以及希望探索Linux在低配设备的优势等因素，就入手了一台使用J1800的瘦客户机。")
st.write("尝试安装的第一个系统还是之前使用的搭载Cinnamon桌面的Linux Mint22，流畅度表现较差。换成了使用Xfce桌面的版本，一些应用有兼容性问题，主题和壁纸切换功能也有缺陷。后面又尝试了轻量化的AntiX Linux和MX Linux，流畅度高但外观和易用性较差。最后尝试了使用Mate桌面的Linux Mint22。Mate桌面是旧版的Linux Mint桌面，相比Cinnamon桌面，没有半透明效果、动画和非整数缩放，流畅度有较大提升。以下为桌面环境截图")
st.image("blog/files/j1800_1.jpg")
st.image("blog/files/j1800_2.jpg")
st.write("软件方面，j1800的视频编解码能力较差，视频硬解只能达到1080p 30帧，录屏可用度不高。浏览器用Edge响应较慢，又换回Firefox。大部分网页打开较慢但可用，谷歌地球等较复杂的webgl网页无法运行。运行NiceGUI文档响应较慢，3d部分掉帧。办公、图像处理软件在低负载时能正常运行。对于一些性能要求较高的软件，Xaos中较复杂的图形无法达到实时运行,Stellarium掉帧但不使用动画功能的情况下在可用水平。")
st.write("本次也尝试了更多开源游戏，但最终可玩性表现较好且画质不太差的只有Openarena、Super Tux Kart和Alien Arena。由于主机只有DP和DVI接口并且即使转接后也无法兼容HDMI屏幕，用了之前的2560x1600分辨率的且不支持其它分辨率的屏幕。全分辨率下游戏纹理清晰度不够且性能要求高，需要添加分辨率供窗口模式使用。添加流程是使用cvt 1920 1200，把输出的参数粘贴到xrandr --newmode后面，最后使用xrandr --addmode +接口编号+参数名称即可。在1920x1200分辨率下，前面几个游戏在预设低画质和高纹理时可以正常使用。")
st.image("blog/files/j1800_3.jpg")
st.image("blog/files/j1800_4.jpg")
st.image("blog/files/j1800_5.jpg")
st.write("本次更换物理机的尝试虽然实现了大部分预期功能，但如果用于正式的低功耗Linux设备，新一些的n100和其它同级别处理器在选择桌面环境时更加自由，在网页和视频应用等方面有明显优势，是更合适的选择。")
st.show()