import streamlit as st
st.set_page_config(layout="wide")
st.title("我使用的Linux发行版")
st.subheader("1.由课程入门", divider=True)
st.write("我入门Linux是因为有课程要用到ROS，ROS虽然有Windows版本但对Windows的支持相对较差，就使用了Ubuntu。Ubuntu使用Gnome桌面，任务栏和软件列表等设计与Windows区别较大，不太习惯。后来课程结束就不再使用Ubuntu了。")
st.write("我使用Ubuntu的体验虽然不太好，但也算是入门了Debian系，了解了apt包管理器、输入法等内容，为后续独立探索其它Linux发行版做了准备。")
st.subheader("2.从主力到弃用", divider=True)
st.write("随着我对开源软件的了解增加，已经在大部分非互联网软件类型中改用开源软件，也希望再次使用开源的Linux系统。")
st.write("查阅资料后，我了解到Linux Mint是易用性较强的Linux发行版，相比大部分发行版外观有一定优势，就安装了Linux Mint22，并成功安装了所有需要使用的软件，部分互联网应用使用星火应用商店安装了wine版本。Linux Mint22使用的是Cinnamon桌面环境，操作上接近Windows系统，使用一些社区主题后总体外观优于当时用的Windows10。当时把Linux Mint22定为主力系统，虽然还有网友反映Windows11稳定性不佳，但考虑到外观优势还是把Windows系统更新到了Windows11。")
st.write("Linux Mint22在使用上也有不少方面体验优于Windows。安装Anaconda后在命令行中可以直接启动Python，而在Windows中需要单独的命令行程序。Linux支持brtfs文件系统，可以实现容量占用较少的快照功能，Linux Mint预装的timeshift能实现按计划创建快照。Cinnamon桌面环境虽然不是轻量化桌面，但流畅度相比Windows系统有优势，窗口可以缩小到较小尺寸并且不会出现还原后尺寸过大的问题。Linux Mint内置应用商店，系统设置中包含换源功能，换源后能快速加载软件详情，我这一时期从软件商店接触到了Xaos、Stellaarium和KDE Marble等优秀的开源软件。在Linux运行Comfyui相比Windows有10%到20%的速度优势，其它软件没有对比。")
st.write("我使用Linux Mint22也遇到了一些问题。Linux Mint内置了smb文件共享功能，但使用其它设备无法连接。Openwebui等在Windows上功能正常的应用也无法在其它设备连接。我用的笔记本电脑的厂商没有适配Linux的风扇转速和键盘灯控制程序，在同类开源软件中也找不到适配的方案。在Windows系统中安装Anaconda后通过conda和pip指令下载都能自动换源，但我在Linux Mint22中只给conda成功换源，pip换源没有效果。Linux上缺少Steam Community302等公开的加速器，在当时对代理服务器了解较少的情况下无法顺利使用GitHub。又因为Windows系统升级到Windows11并使用资源管理器高斯模糊等美化措施后外观有优势，就弃用了Linux。")
st.subheader("3.回归双系统", divider=True)
st.write("后来我了解了代理服务，在完成其它一些项目后有空闲的硬盘，为了进一步探索Linux和在Windows有故障时准备恢复措施，决定安装一个Linux发行版组双系统。")
st.write("开始时为了尝试平铺和浮动兼备的窗口管理，选择了使用测试版Cosmic DE的Pop!_OS。实际使用发现Cosmic DE的窗口管理的确能提高效率，但这一版本的Pop!_OS也存在不少软件无法正常使用，软件安装使用flatpak的空间占用较大，因此决定弃用。")
st.write("个人感觉DDE15桌面的外观比较好，就尝试了GXDE。GXDE是基于Debian12的使用DDE15桌面的Linux发行版，但在GXDE出现无法使用深色模式、系统内置播放器播放HDR视频卡顿的问题。又测试了Debian v23，DDE23桌面的外观不如DDE15，并且使用时遇到了系统内置播放器在界面缩放大于100%时播放视频分辨率下降的问题，也决定弃用了。")
st.write("后面了解到Fedora是偏上游并且易用的系统，使用Budgie桌面的版本操作方式接近Windows并且外观比较好，就安装了Fedora。相比deb系，在软件商店安装软件时不需要输入密码，安装快很多。但使用时遇到一个严重问题：系统自带的硬件解码只支持英特尔处理器，但我的电脑使用的是AMD的处理器，无法使用硬件解码，因此弃用了Fedora。")
st.write("最后还是决定装回Linux Mint，尝试了基于Debian的LMDE6，但出现了安装时没有中文以及部分软件功能不完善的问题（例如Xaos没有提供分形实例），就换成之前用过的Linux Mint22。这一次进一步探索了软件商店中的游戏列表，发现Linux上有比较完善的开源3D游戏，我玩的时间比较长的有Openarena和SuperTuxKart。")
st.subheader("4.新的物理机", divider=True)
st.write("（考虑到两个配置都有外观更好的桌面环境，为节省篇幅已移除这一部分图片）由于我目前性能需求高的应用都在Windows上部署，AI视频等应用需要长时间运行，切换到Linux时不能继续使用这些应用，并且考虑到使用REFS数据盘、时间不统一以及希望探索Linux在低配设备的优势等因素，就入手了一台使用J1800的瘦客户机。")
st.write("尝试安装的第一个系统还是之前使用的搭载Cinnamon桌面的Linux Mint22，流畅度表现较差。换成了使用Xfce桌面的版本，一些应用有兼容性问题，主题和壁纸切换功能也有缺陷。后面又尝试了轻量化的AntiX Linux和MX Linux，流畅度高但外观和易用性较差。最后尝试了使用Mate桌面的Linux Mint22。Mate桌面是旧版的Linux Mint桌面，相比Cinnamon桌面，没有半透明效果、动画和非整数缩放，流畅度有较大提升。")
st.write("软件方面，j1800的视频编解码能力较差，视频硬解只能达到1080p 30帧，录屏可用度不高。浏览器用Edge响应较慢，又换回Firefox。大部分网页打开较慢但可用，谷歌地球等较复杂的webgl网页无法运行。运行NiceGUI文档响应较慢，3d部分掉帧。办公、图像处理软件在低负载时能正常运行。对于一些性能要求较高的软件，Xaos中较复杂的图形无法达到实时运行,Stellarium掉帧但不使用动画功能的情况下在可用水平。")
st.write("本次也尝试了更多开源游戏，但最终可玩性表现较好且画质不太差的只有Openarena、Super Tux Kart和Alien Arena。由于主机只有DP和DVI接口并且即使转接后也无法兼容HDMI屏幕，用了之前的2560x1600分辨率的且不支持其它分辨率的屏幕。全分辨率下游戏纹理清晰度不够且性能要求高，需要添加分辨率供窗口模式使用。添加流程是使用cvt 1920 1200，把输出的参数粘贴到xrandr --newmode后面，最后使用xrandr --addmode +接口编号+参数名称即可。在1920x1200分辨率下，前面几个游戏在预设低画质和高纹理时可以正常使用。")
st.write("本次更换物理机的尝试虽然实现了大部分预期功能，但如果用于正式的低功耗Linux设备，新一些的n5095和其它同级别处理器在选择桌面环境时更加自由，在网页和视频应用等方面有明显优势，是更合适的选择。")
st.subheader("5.最佳Material Design桌面环境", divider=True)
st.write("由于对Cinnamon桌面环境的外观不太满意，就决定尝试Budgie桌面环境。在Linux Mint有软件包但存在依赖项冲突，在EndeavourOS安装切换不了桌面环境，Ubuntu有对应第三方发行版但用了一些Ubuntu软件导致外观不一致且桌面环境为外观接近Gnome3的版本，就尝试了Solus Linux。")
st.write("当前版本的Budgie桌面环境用了不少阴影效果（任务栏阴影需要开启内置主题），再加上图标设计，算是Linux上最好的Material Design方案，个人认为在Linux中也是外观最好的设计。另一个优势是比较轻量化，流畅度明显优于Cinnamon，更换转接口连接1080p屏幕后算是在j1800唯一达到可用水平的有动画的桌面环境，n5095以上配置应该能在高分辨率达到比较高的流畅度，改用dvi转hdmi接上1080p屏幕用j1800就比较流畅了，并且用100%缩放加上大号字体能做到比较合适的界面大小。不过功能方面，由于文本编辑器等程序折叠了菜单，功能性不如Cinnamon桌面环境。另外也有不支持非整数缩放和只有左右分屏的功能缺陷。")
st.image("files/bg1.jpg")
st.image("files/bg2.jpg")
st.image("files/bg3.jpg")
st.write("Solus Linux从Debian二次开发但不支持deb软件包，虽然不少知名开源软件可以在软件源找到但有一部分需要另外更换。目前通过clash-for-linux-install项目使用代理，重启后需要手动设置系统代理。Ollama和Chatbox等应用使用安装脚本或appimage就不受影响。Timeshift,Edge和Github Desktop等应用没有对应版本就无法安装。")
st.write("在主力机也尝试在Debian系统安装Budgie桌面环境，在界面以外还提供了Budgie风格的设置应用，安装主题后能切换到Material Design风格，新立得软件包管理器和系统监视器等应用也切换了风格，但界面本身还是默认风格，文件管理器等应用没有对应的Budgie版本。")
st.subheader("6.探索Cinnamon主题", divider=True)
st.write("在主力机使用时，考虑到2.5k屏幕使用无非整倍缩放桌面环境的效果较差，就继续使用Linux Mint。更换主题时发现部分Cinnamon主题有窗口主题，具有较好的外观表现，就检查了所有主题，表现较好的有以下两个（已排除无窗口边框的主题），其中material主题外观优势较为明显")
st.image("files/CT1.jpg")
st.image("files/CT2.jpg")
st.subheader("7.iStoreOS与存算分离", divider=True)
st.write("虽然j1800能用外观较好的Solus Linux，但兼容性较差，又考虑到Linux系统使用各类局域网共享的权限设置比较麻烦，就装了iStoreOS且部署了分离出存储功能，主要部署了smb和Jellyfin，客户端直接在浏览器使用以避免转码。如果以后弃用Windows，这一形式仍然能保持比较好的体验。")
st.write("iStoreOS也有对http以及常见web开发框架的支持，其它web依赖项大多可以通过cdn导入。部署python程序比较麻烦，直接安装时无法安装需要编译的python包，安装conda也会遇到bash支持的问题。不过iStore上有一个带远程桌面的Ubuntu，可以安装conda，但由于过度精简，不兼容clash verge或clash for linux install等程序，不过提前在iStoreOS启动openclash也能使用代理。vscode能用但延时长，而iStore上的使用web的codeserver无法显示界面。最终改用Docker部署Streamlit应用。")
st.write("根据说明，iStoreOS的Ubuntu镜像来源于kasmtech的仓库，kasmtech/workspaces-images和kasmtech/workspaces-core-images仓库分别提供了有桌面环境和无桌面环境的可通过http串流的Linux镜像。不过对比仓库的说明，iStoreOS的Ubuntu镜像的确进行了精简。")
st.write("另外入手了一台j4125迷你主机作为备用机。视频输出高于1080p时容易掉帧，但限制在1080p时体验好不少。可以流畅运行Cinnamon桌面，解码1080p 60帧/2.5k 30帧视频，进行1080p 30帧录屏，全高画质运行Openarena，以第5级画质运行Supertuxkart，Stellarium达到14帧，Xaos超过24帧。")
st.write("考虑到Jellyfin生成缩略图流畅度问题以及方便在不同设备使用一个Linux桌面，后面改为在j4125部署iStoreOS，j1800安装xfce桌面的solus linux并连接iStoreOS上的Ubuntu镜像。需要注意的是默认视频模式降分辨率，为保证效果可以改为不降分辨率并更改压缩比，播放视频尽量在物理机进行。输入法方面需要开启使用系统输入法选项而非使用虚拟机的输入法。这样部署的缺点是只能用外观较差的xfce桌面。")
