import streamlit as st
st.set_page_config(layout="wide")
st.title("实时分形软件")
st.write("实时分形虽然画质较低，但具有较高的操作自由度。为了减少容量占用，本页面的视频使用720p分辨率。")

st.subheader("1.2D分形", divider=True)
st.write("2D分形常用的跨平台开源软件是Xaos，提供了不少示例。主流配置可以在2.5k分辨率流畅运行。")
video_file1 = open("files/xaos_1.mp4", "rb")
video_bytes1 = video_file1.read()
st.video(video_bytes1)
video_file2 = open("files/xaos_2.mp4", "rb")
video_bytes2 = video_file2.read()
st.video(video_bytes2)
video_file3 = open("files/xaos_3.mp4", "rb")
video_bytes3 = video_file3.read()
st.video(video_bytes3)

st.subheader("2.3D分形", divider=True)
st.write("3D分形常用的跨平台开源软件是Mandelbulber2，主流配置需要降分辨率才能达到较快的响应速度，为了加快响应应当优先考虑使用高性能的CPU。以下视频在800x600分辨率运行。")
video_file4 = open("files/mandelbulber_1.mp4", "rb")
video_bytes4 = video_file4.read()
st.video(video_bytes4)
video_file5 = open("files/mandelbulber_2.mp4", "rb")
video_bytes5 = video_file5.read()
st.video(video_bytes5)
video_file6 = open("files/mandelbulber_3.mp4", "rb")
video_bytes6 = video_file6.read()
st.video(video_bytes6)

