import streamlit as st

st.title("绘画模型和视频模型使用案例")
st.write("相比复杂的工作流，我更偏向使用功能完善的模型通过较简单的流程做到较好的效果。这部分也只展示文生图和文生视频流程得到的内容。由于之前生成的内容已发布到社交媒体，为了避免内容重复，这里只展示新生成的内容。之前的图片内容发布在https://www.xiaohongshu.com/user/profile/6605a535000000000b00c4d2? ，视频默内容发布在https://space.bilibili.com/478036060? 和https://www.acfun.cn/u/76077623 （包含其它类型的图片和视频）")
st.subheader("1.绘画模型", divider=True)
st.write("我另外创建了Gallery Without Prompt项目，展示使用由Flux.1 dev文生图再由Flux.1 schnell图生图的流程在不填写提示词时得到的图片：https://william7004-gallery-without-prompt.streamlit.app")
st.write("Hunyuan Video Gallery Without Prompt项目，展示使用Hunyuan Video在不填写提示词时得到的图片和视频：https://william7004-hunyuan-video-gallery-without-prompt.streamlit.app")
st.write("以下图片使用Flux.1 dev生成，分辨率1536x1024，主要包含各种风格中比较有代表性的内容。图片注释为提示词。")
st.image("ai-note/files/p1.jpg", caption="an anime girl with white feather wings wearing lace dress holding a staff flying in the sky surrounded by seagulls,")
st.image("ai-note/files/p2.jpg", caption="a luxury cruise on a river through a city with skyscrapers,evening,")
st.image("ai-note/files/p3.jpg", caption="a castle surrounded by autumn forest on a cliff near sea,")
st.image("ai-note/files/p4.jpg", caption="trees,paths covered by steel and a pond in a large sci-fi building with steel frame and glass dome near a city with sci-fi buildings on Mars,")
st.image("ai-note/files/p5.jpg", caption="model cars on a road in a model city with European-style buildings,macrophotography")
st.image("ai-note/files/p6.jpg", caption="skyscrapers in the CBD among European-style architecture in a city,aerial photography,")
st.image("ai-note/files/p7.jpg", caption="a temple on a mountain above clouds,an old man wearing white Han Chinese clothing standing on a boat floating in the sky,sunrise,traditional Chinese painting,")
st.image("ai-note/files/p8.jpg", caption="a business jet flying over clouds,aerial photography,sunrise,")
st.image("ai-note/files/p9.jpg", caption="a modern villa in a cave in a cliff,")
st.image("ai-note/files/p10.jpg", caption="a woman wearing fashion white dress standing sitting on a leather sofa near glass table in a saloon with walls made of granite in modern valley，Floating Stairs on the side of the saloon,")
st.subheader("2.视频模型", divider=True)
st.write("以下视频使用Hunyuan Video生成（fp8量化，使用Enhance A Video)，分辨率1280x720 12fps，主要包含对几种运动场景的测试。")
video_file = open("ai-note/files/v1.mp4", "rb")
video_bytes1= video_file.read()
st.video(video_bytes1)
st.write("提示词：Offroad cars crossing a misty valley, with fog rolling over the rugged terrain. ")
video_file = open("ai-note/files/v2.mp4", "rb")
video_bytes2= video_file.read()
st.video(video_bytes2)
st.write("提示词：A sports car running on a cobblestone street in a medieval town with ancient buildings.")
video_file = open("ai-note/files/v3.mp4", "rb")
video_bytes3= video_file.read()
st.video(video_bytes3)
st.write("提示词：A light plane flying above a winding river, its waters sparkling in the sun.")
video_file = open("ai-note/files/v4.mp4", "rb")
video_bytes4= video_file.read()
st.video(video_bytes4)
st.write("提示词：a woman wearing jacket and jeans walking in autumn forest,cinematic,")
st.subheader("3.Hunyuan Video图片生成", divider=True)
st.write("通过Hunyuan Video Wrapper插件无法正常生成单帧。而comfyui官方版本提供的Hunyuan Video支持虽然缺少Enhance a Video带来的锐度提升，但可以正常生成单帧。目前已切换到官方版本的Hunyuan Video工作流并使用gguf格式模型。")
st.write("经测试Hunyuan Video可以正常生成的最大图片分辨率约为1600x896，考虑显存占用可以降低到1584x896。虽然分辨率不及Flux.1并且对细节较多的场景的生成有问题,但光照和材质表现有较大优势，已决定弃用Flux.1。以下是一些案例：")
st.image("ai-note/files/h1.jpg", caption="a girl wearing jacket and shorts standing on a cliff near sea")
st.image("ai-note/files/h2.jpg", caption="a man playing guitar on a bench in a park")
st.image("ai-note/files/h3.jpg", caption="a woman walking in supermarket")
st.image("ai-note/files/h4.jpg", caption="an offroad car on rocky road in autumn forest")
st.show()