import streamlit as st

st.title("绘画模型和视频模型")
st.subheader("1.绘画模型", divider=True)
st.write("由于早期的绘画模型都是开源模型并且有工作流的积累，虽然一些闭源绘画模型在测试中表现更好，但开源绘画模型一直是主流，本文暂时只讨论开源绘画模型。")
st.write("开源绘画模型中细节最好的是Flux.1 dev,生成相对较慢，但在细节较多的场景表现更好，实测最大实用分辨率为1536x1024。Flux.1 schnell在一些场景中最大实用分辨率能达到2560x1440并且生成更快。Hunyuan Video也可以用于图片生成，光照表现有优势但分辨率较低且不适合生成细节较多的图片。生成高分辨率内容效果最好的是Sana 1.6b，最高支持4096x4096分辨率。")
st.subheader("2.视频模型", divider=True)
st.write("闭源视频模型中，最新的Veo2和Pica2等模型有比较好的动作生成效果，并且提供了不少一致性功能。开源模型中尚未正式发布的Meta Moviegen应该也会提供较多的一致性控制功能。")
st.write("一些视频模型有一些有优势的特性。创作长视频需要保证不同片段的一致性，Sora虽然生成效果没有优势，但提供了story board功能，可以实现多个片段的内容一致。Vidu2.0提高了生成速度，降低了成本。")
st.write("开源视频模型中效果最好的有Hunyuan Video和Cosmos，与最新的商业视频模型有一定差距。在comfyui部署时，Hunyuan Video用8g显存能生成21帧896p视频；Cosmos只支持720p分辨率，8g显存能生成81帧，速度比前者快不少。LTX Video在生成速度上有优势，但出片率和效果不如Hunyuan Video。")
st.subheader("3.视频增强模型", divider=True)
st.write("目前效果比较好的视频增强模型主要是VEnhancer，理论上可以实现任意分辨率和帧率的视频增强，但显存占用较大，随着开源视频模型可以生成的分辨率提升，已不必使用VEnhancer。")
st.subheader("4.模型部署", divider=True)
st.write("绘画模型、视频模型和一些其它类型的模型一般使用ComfyUI部署。主要优势是有显存优化并且可以提供插件适配更多模型。为了方便管理插件和运行环境，可以使用绘世等第三方整合包。")
st.show()